### ISSUE TITLE
Error 404 Not Found #nginx

### ISSUE THREAD

**Issue by aanzebua** [laravel-vue-book/be-fullstack-developer#1]
saya udah coba ubah file laradock/nginx/sites/default.conf

`root /var/www/public;`

menjadi

`root /var/www;`

Tapi masih tetap error

**Comment by aasumitro** [comment]
coba buat file configurasi baru aja pak 

misalnya laradock/nginx/sites/e-store.conf yang misalnya nanti di akses via e-store.test
terus isi file configurasi tsb.

`server {

    listen 80;
    listen [::]:80;

    server_name e-store.test;
    root /var/www/e-store/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
}
`

**Comment by aasumitro** [comment]
coba buat file configurasi baru aja pak, terus yang file default.conf tetap dibiarkan default.

*buat baru -> misalnya laradock/nginx/sites/e-store.conf yang  nantinya di akses via **e-store.test**
terus isi file configurasi tsb.

```
 server {

    listen 80;
    listen [::]:80;

    server_name e-store.test;
    root /var/www/e-store/public;
    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass php-upstream;
        fastcgi_index index.php;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        #fixes timeouts
        fastcgi_read_timeout 600;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt/;
        log_not_found off;
    }

    error_log /var/log/nginx/laravel_error.log;
    access_log /var/log/nginx/laravel_access.log;
} 
```

</br>
<p align="center">
   <img src="https://raw.githubusercontent.com/aasumitro/gif-host/master/GIF%20VSCode/Screenshot%20from%202018-10-19%2012-05-11.png" width="250">
</p>
</br>

**Comment by azamuddin** [comment]
Ada beberapa hal yang perlu dipastikan
1. projek laravelnya sudah dibuat. 
2. root pada `laradock/nginx/sites/default.conf` diarahkan ke folder projek bukan folder laradock.

Misal:
+ laravel-projects/
    + laradock
    + toko-online

maka root diarahkan ke `/var/www/toko-online`
