### ISSUE TITLE
inconsistent update slug

### ISSUE THREAD

**Issue by candrasaputra** [laravel-vue-book/be-fullstack-developer#3]
Di halaman 229 - 230

Pada contoh edit kategori.
Input fild slug active yang artinya dapat di edit.
di dalam function update controller category juga terdapat variable untuk menampung slug.

` $slug = $request->get('slug');`

Tetapi sebelum printah save kategori, slug di ubah dengan menggunakan name

`$category->slug = str_slug($name);`

Sehingga edit slug bisa di bilang PERCUMA.

**Comment by azamuddin** [comment]
Terima kasih atas masukannya. Seharusnya untuk edit category, tidak perlu menggunakan `str_slug($name)`.
